version: '3.0'
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 5672:5672 # port for the daemon API
      - 15672:15672 # port for the RabbitMQ management interface
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  consumer:
    build: consumer
    depends_on:
      - rabbitmq
    ports:
      - 9422:9422  # expose the Prometheus metrics port
    command: python consumer.py -p 5672 -s rabbitmq
    restart: on-failure
  
  producer:
    build: producer
    depends_on:
      - rabbitmq
    # run the producer continuously sending messages every 20 seconds
    command: 'python producer.py -p 5672 -s rabbitmq -m "Hello"'
    restart: on-failure
  