auth:
  username: "guest"
  password: "guest"

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 30s
    scrapeTimeout: 10s

rabbitmqExporter:
  enabled: true
  service:
    type: ClusterIP
    port: 9419
  serviceMonitor:
    enabled: true
    interval: 30s
    scrapeTimeout: 10s
