apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-consumer-service-monitor
  namespace: {{ .Values.monitorNamespace }}
  labels:
    release: {{ $.Release.Name | quote }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      name: {{ .Release.Name }}-consumer
  endpoints:
  - port: metrics 
    interval: 15s
    path: /metrics
